# Generated by Django 5.2.8 on 2025-11-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='authapp_tra_user_id_7d1e07_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='authapp_tra_transac_6cfac2_idx',
        ),
    ]
